### ISSUE TITLE
permission error while init Browser()

### ISSUE THREAD

**Issue by gagahan** [nateshmbhat/webbot#2]
I get permission error when i try to init Browser().
```
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>> from webbot import Browser
>> Browser()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/webbot/webbot.py", line 45, in __init__
    os.chmod(driverpath , 0o755 ) 
PermissionError: [Errno 1] Operation not permitted: '/usr/local/lib/python3.5/dist-packages/webbox/drivers/chrome_linux'
```

**Comment by nateshmbhat** [comment]
Go to the folder `/usr/local/lib/python3.5/dist-packages/webbox/drivers/chrome_linux` and give the executable permission to the `chrome_linux` using this command in your terminal .

`chmod +x chrome_linux`

**Comment by pvandegeer** [comment]
I'm getting the same error. Running as su returns a FileNotFoundError.
There is no chrome_linux at the specified path. It is at /usr/local/lib/python3.5/dist-packages/webbot/drivers/chrome_linux, not webboX
