### ISSUE TITLE
I can't install webbot in my pc

### ISSUE THREAD

**Issue by TWO-ONE-21** [nateshmbhat/webbot#23]
please help me, i can't install this module.
I am using windows 10. 
the error is
pip install webbot
Collecting webbot
  Could not find a version that satisfies the requirement webbot (from versions: 0.0.1.win-amd64)
No matching distribution found for webbot
You are using pip version 18.1, however version 19.2.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

**Comment by nateshmbhat** [comment]
This is not webbot's issue please upgrade your pip and then check.

**Comment by TWO-ONE-21** [comment]
#I was upgraded my pip, 

C:\Users\LENOVO>pip install --upgrade setuptools
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting setuptools
  Downloading https://files.pythonhosted.org/packages/b2/86/095d2f7829badc207c893dd4ac767e871f6cd547145df797ea26baea4e2e/setuptools-41.2.0-py2.py3-none-any.whl (576kB)
     |UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU| 583kB 322kB/s
Installing collected packages: setuptools
  Found existing installation: setuptools 41.0.1
    Uninstalling setuptools-41.0.1:
      Successfully uninstalled setuptools-41.0.1
Successfully installed setuptools-41.2.0

#and, It still can't to install :( 
C:\Users\LENOVO>pip install webbot
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting webbot
  ERROR: Could not find a version that satisfies the requirement webbot (from versions: 0.0.1.win-amd64)
ERROR: No matching distribution found for webbot
