### ISSUE TITLE
Does it work on a headless server?

### ISSUE THREAD

**Issue by TravelTrader** [nateshmbhat/webbot#32]
First: **I LOVE IT!**
With this library, everything gets easy and works!

I plan to use it on a server without any screen. Does the library work in a headless browser?
What are the requirements?

First check results in:
```
[...]
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
  (Driver info: chromedriver=2.39.562737 (abcdefg),platform=Linux 4.15.0-64-generic x86_64)
```
**UPDATE:**
When I am in the Python shell nothing happens after `web = Browser()` and I have to CTRL-C the shell to get out...

Thank you for your help!

**Comment by DeathwingTheBoss** [comment]
I seem to have the same issue. Stuck at web = Browser() nothing happens.

**Comment by nateshmbhat** [comment]
yes , it works on a headless server also. There will be some option regarding to configure the x-window environment to run gui programs.

Exploring that would help you.
