### ISSUE TITLE
find_elements returning too many things?

### ISSUE THREAD

**Issue by doubledrat** [nateshmbhat/webbot#36]
it's probably me not understanding how this is supposed to work, but if I issue the following javascript

`document.querySelectorAll('div[class^=addressContainer]')
`

I get 3 elements returned

If I do this in webbot, I get 64

`w.find_elements(css_selector='div[class^=addressContainer]')`

However if I do this

`w.driver.find_elements_by_css_selector('div[class^=addressContainer]')`

it returns 3 elements

what am I doing wrong?

**Comment by nateshmbhat** [comment]
There is a `loose_match = True` parameter which defaults to true.
Try making it false and check.

**Comment by nateshmbhat** [comment]
If you want to run css query selector , then you can directly use the `driver` object from the webbot instance.

`
web = Browser()
web.driver.find_element_by_css_selector("div[class^=addressContainer]")
