### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by TravelTrader** [nateshmbhat/webbot#38]
I am using the `webbot` module in many projects.
Now I wanted to use it on another system (both Ubuntu 18.04) and with the simple basic code:

```
import webbot as Browser
import time

web = Browser(showWindow=False)
time.sleep(1)

web.quit()
```

I do get this error message: `TypeError: 'module' object is not callable`

Any ideas how to solve it?
Thanks a lot.

__Update:__
The same code and much more useful codes are running on other systems of mine. So I am confused what it means. I do not get an error for just using `import webbot as Browser`.

**Comment by nateshmbhat** [comment]
can you check with the latest release again ?

**Comment by TravelTrader** [comment]
I just upgraded `webbot` again but it does not work.
What does the error message mean? Is anything missing on my headless server?
Or isn't it possible to use over ssh?
Would be great to know the reason behind this error message to find a solution?

Or can you list again the requirements for `webbot` to work or what requirements are needed to not get this error message?

Thank you!

**Comment by nateshmbhat** [comment]
Try to follow the below steps :


#install Xvfb
sudo apt-get install xvfb

#set display number to :99
Xvfb :99 -ac &
export DISPLAY=:99    

#you are now having an X display by Xvfb


Let me know if the above method is working...

**Comment by TravelTrader** [comment]
Thanks but the same error...

**Comment by millefalcon** [comment]
> I am using the `webbot` module in many projects.
> Now I wanted to use it on another system (both Ubuntu 18.04) and with the simple basic code:
> 
> ```
> import webbot as Browser
> import time
> 
> web = Browser(showWindow=False)
> time.sleep(1)
> 
> web.quit()
> ```
> 
> I do get this error message: `TypeError: 'module' object is not callable`
> 
> Any ideas how to solve it?
> Thanks a lot.
> 
> **Update:**
> The same code and much more useful codes are running on other systems of mine. So I am confused what it means. I do not get an error for just using `import webbot as Browser`.

I recently came across this issue, and another user helped me realize the problem that this is a user error.
They were using it as,

` import webbot as Browser`.

The correct one i think is,

`from webbot import Browser`.

Hope this helps.

**Comment by TravelTrader** [comment]
Thanks @millefalcon!
That solved the problem. It was just a wrong import from the library.
