### ISSUE TITLE
Can't open a new tab despite using 'new_tab(url)' method

### ISSUE THREAD

**Issue by revshell0** [nateshmbhat/webbot#41]
Hi, I am not able to open a new tab despite using the available method _new_tab(url)_.

Let's say this is the code snippet:

`from webbot import Browser

driver = Browser()
driver.go_to('https://google.com')
driver.new_tab(url='https://github.com')`

How do I get this to work? Could anyone please guide? Thanks.

**Comment by DankSideSparkles** [comment]
The current package in the index isn't updated. However, you can clone the repo directly, and import it into the project. For the time being. @nateshmbhat @revshell0

**Comment by revshell0** [comment]
@DankSideSparkles Got it. Thanks.

@nateshmbhat Please update the package asap. Oh & thanks for Webbot, it has really been very useful.

**Comment by nateshmbhat** [comment]
Its now working in the latest release.

**Comment by revshell0** [comment]
@nateshmbhat Thanks for the prompt action! :)
