### ISSUE TITLE
exists(id=' ') method always returns True

### ISSUE THREAD

**Issue by revshell0** [nateshmbhat/webbot#42]
@nateshmbhat The **exists()** method with any constructor inside it, always returns True despite entering random values.

You can try this code snippet. It always returns True.

```
from webbot import Browser

driver = Browser()
driver.go_to('https://github.com/login')

print(driver.exists(id='1234qwerty'))
print(driver.exists(css_selector='input[name="8888888"]'))
print(driver.exists(xpath='//input[@id="asdfg"]'))
```

Could you please check and fix this bug? My QA code makes extensive use of 'exists()' method. It will be very helpful. Thanks.

**Comment by nateshmbhat** [comment]
Hey can you check if this is happening in previous versions of webbot ?

**Comment by nateshmbhat** [comment]
Can you check if this is happening in previous versions of webbot?

**Comment by revshell0** [comment]
@nateshmbhat I think I made a mistake and I might have misled you. I think this is not an issue.

The exists() method expects a text as a mandatory argument, and all it does is - it checks whether or not the text exists at the location specified by the constructor.

For example:
`driver.exists('abc@gmail.com', id='email')` checks whether text 'abc@gmail.com' exists in the 'email' element.
Similarly, `driver.exists('hell yeah')` checks whether the text exists anywhere on the page.

If what I said just now is correct, then this issue is invalid and you can close it.

I originally assumed that this method is used to identify whether the element itself exists or not.

**Comment by revshell0** [comment]
Conversely, could you please tell me.. is there a way to identify whether an element itself exists or not?

I want my bot to enter some text in an input field only if the field exists in the first place.

For example,

```
if username element exists:
       enter the value 'admin' in that field.
else:
       pass
```

How do I achieve this? Thanks.

**Comment by nateshmbhat** [comment]
You can use the driver object directly.

web.driver.find_element_by_id()

There are methods on the driver object to find element by ID, css and XPath.

**Comment by revshell0** [comment]
@nateshmbhat What I had originally written was not a bug. I misunderstood it.

This exists() method expects a text as an argument and that text is actually the name of the element itself and NOT the value present within the element.

Meaning, `driver.exists('username', id='username')` checks whether 'username' is infact the name of the element with 'username' id. That's how you check whether an element exists or not.

Cheers!
