### ISSUE TITLE
Couldn't find the option to configure proxy in webbot

### ISSUE THREAD

**Issue by revshell0** [nateshmbhat/webbot#43]
@nateshmbhat How can I configure a proxy to redirect the traffic through my specified location?

Say, I want the traffic to go through my Burp proxy tool hosted at http://localhost:8080, how do I make it happen?

This is one of the biggest requirements while doing QA (Quality Analysis) of a website.

Please advise. Thanks.

**Comment by revshell0** [comment]
@nateshmbhat Below is the equivalent code snippet in Selenium.

```
from selenium import webdriver

PROXY = "http://localhost:8080"

chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--proxy-server=%s' % PROXY)

driver = webdriver.Chrome(options=chrome_options)
driver.get("https://github.com")
```

If you can somehow incorporate this in webbot, maybe as an additional constructor, that would be awesome.

Something like:

```
from webbot import Browser
driver = Browser(proxy = "http://localhost:8080")
```

Please consider this request. Thanks!

**Comment by nateshmbhat** [comment]
Sure. Adding it. Thanks for the suggestion.

**Comment by revshell0** [comment]
@nateshmbhat woahhhhh!!!! that was quick! thank you for the prompt action! I would definitely recommend this library to all my colleagues!
