### ISSUE TITLE
pip installation not working from Mac OS X

### ISSUE THREAD

**Issue by philshem** [nateshmbhat/webbot#6]
Related to this [PyPi issue](https://github.com/pypa/pypi-legacy/issues/800), 
`webbot` installation via pip on Mac OS X Mojave is not working with Python 2.

Error message:

     Could not find a version that satisfies the requirement webbot (from versions: 0.0.1.win-amd64)

From the [PyPi Issue](https://github.com/pypa/pypi-legacy/issues/800):

> The other (webbot-0.0.1.win-amd64.zip) is a source distribution, but the version number portion (0.0.1.win-amd64) is either invalid and hence getting rejected, or specifies that the source is for a specific platform different than the one you're running on, and also getting rejected (honestly, I'm not sure if "platform tags" are allowed/respected in source distribution filenames).

And potential solution:

> So the fix is either to use a recent version of pip on Python 3, or to upload new wheels and source distributions with correct filenames and metadata.

Or, if webbot is only supported by Python 3, it would be good to write so in the documentation.

**Comment by benhc123** [comment]
+1
not working for me
:(

**Comment by nateshmbhat** [comment]
The docs are updated.
