### ISSUE TITLE
How to perform right click using webbot

### ISSUE THREAD

**Issue by manwapri** [nateshmbhat/webbot#73]
I want to right click on a page and I am not able to find any solution for it.
I tried Browser().Context_Click, but it is not available.

Could any one please suggest on this.

**Comment by joshiayush** [comment]
```python
from selenium.webdriver import ActionChains

actionchains = ActionChains(Browser().driver)
actionchains.context_click(your_url).perform()
```

**Comment by manwapri** [comment]
Thansk joshiayush, for your response.

I have modified the webbot code for right click fuctionality,
You can see this code in pull request.

**Comment by joshiayush** [comment]
> ```python
> from selenium.webdriver import ActionChains
> 
> # Browser object has the driver instance publicly available so use it
> actionchains = ActionChains(Browser().driver)
> actionchains.context_click(your_url).perform()
> ```

I just noticed #75 pull request, it's been a lot of time but the PR is not merged yet. If the code remains unchanged the above method will work.
