### ISSUE TITLE
How to change browser to firefox?

### ISSUE THREAD

**Issue by mushlih-almubarak** [nateshmbhat/webbot#77]
How to change browser to firefox?

**Comment by joshiayush** [comment]
You can't because there is no support for any other browser besides Google Chrome. You should open a feature request for that. Thanks!

**Comment by manwapri** [comment]
Try this:

Step 1: check your browser version
		For Chrome:  go to Menu -> Help -> About Google Chrome

Step 2: Download browser driver as per the browser version from below link
Chrome:	        https://sites.google.com/a/chromium.org/chromedriver/downloads
Edge:		https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/
Firefox:		https://github.com/mozilla/geckodriver/releases
Safari:		https://webkit.org/blog/6900/webdriver-support-in-safari-10/		

Step 3: extract the driver file and save it to,
		C:\Users\%USERNAME%\AppData\Local\Programs\Python\Python39\lib\site-packages\webbot\drivers\

Step 4: In drivers forlder, make copy of chrome_windows (Simply copy the file & paste it in same folder)
		new file will be like "chrome_windows - Copy.exe"
		and delete the original "chrome_windows.exe"

Step 5: Rename the extracted file "chromedriver.exe" or any other name to "chrome_windows.exe"

**Comment by mushlih-almubarak** [comment]
Thank you very much!
