### ISSUE TITLE
 'Browser' object has no attribute 'find_elements'

### ISSUE THREAD

**Issue by ghost** [nateshmbhat/webbot#8]
**My code:** 
```
from webbot import Browser

web = Browser()
web.find_elements('Web Development')
```
**Output**
```
web.find_elements('Web Development')
AttributeError: 'Browser' object has no attribute 'find_elements'

```

**Comment by nateshmbhat** [comment]
The updated version is not pushed to `pip` yet , will do so. You can clone this repository for time being or use `pip install git+https://github.com/nateshmbhat/webbot` for now.

**Comment by nateshmbhat** [comment]
you can use the methods. the package is updated.
