### ISSUE TITLE
Browser file not found

### ISSUE THREAD

**Issue by Iamnottryingmybest** [nateshmbhat/webbot#9]
using the sample code I have been getting the following output
`Traceback (most recent call last):
  File "C:\Users\user\Desktop\file.py", line 2, in <module>
    web = Browser()
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\webbot\webbot.py", line 50, in __init__
    os.chmod(driverpath , 0o755 )
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\webbot\\drivers\\chrome_windows'`

The file does exist the in the given directory, I'm assuming that I've bugged up the installation somehow?

(selenium is installed, maybe also an issue with pip?)

**Comment by vishalvsparrow** [comment]
Facing the same issue

**Comment by hstabeno** [comment]
The fix I used was edit the webbot.py found at 
'C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\webbot\\webbot.py'

and change line 45 from:
 `driverfilename = 'chrome_windows'` -> `driverfilename = 'chrome_windows.exe' `

**Comment by SolitudalDeveloper** [comment]
I made a pr to fix this here. 
https://github.com/nateshmbhat/webbot/pull/10#issue-256067877

 
> The fix I used was edit the webbot.py found at
> 'C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\webbot\webbot.py'
> 
> and change line 45 from:
> `driverfilename = 'chrome_windows'` -> `driverfilename = 'chrome_windows.exe' `

**Comment by nateshmbhat** [comment]
The issue is fixed .
